version: '2'
services:
  restaurant-app:
    image: restaurant
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://restaurant-mysql:3306/restaurant?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8183:8183
  restaurant-mysql:
    extends:
      file: mysql.yml
      service: restaurant-mysql
